- name: "install dependencies"
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    update_cache: yes
    state: latest
- name: "Add docker key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: "Add docker repository"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    state: present
- name: "Install Docker Engine"
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    update_cache: yes
    state: latest
- name: "Add user to docker group"
  user:
    name: docker
    shell: /bin/bash
    group: docker
    state: present

